#!/usr/bin/env bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

usage() {
  cat << EOF # remove the space between << and EOF, this is due to web plugin issue
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] -p param_value arg1 [arg2...]

Script description here.

Available options:

-h, --help      Print this help and exit
-v, --video     Play video
-p, --playlist  Some param description
-s, --search    Search youtube for string and play
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

parse_params() {
  # default values of variables set from params
  param=''
  search=''
  VIDEO=false

  while :; do
    case "${1-}" in
    -h | --help) usage ;;
    -v | --video) VIDEO=true;;
    --no-color) NO_COLOR=1 ;;
    -p | --playlist) # example named parameter
      param="${2-}"
      shift
      ;;
    -s | --search) # example named parameter
      search="${2-}"
      shift
      ;;
    -?*) die "Unknown option: $1" ;;
    *) break ;;
    esac
    shift
  done

  args=("$@")

  return 0
}

parse_params "$@"
setup_colors

# Search and Playlist can't both be set.
[[ ! -z "${search}" ]] && [[ ! -z "${param}" ]] && die "Can't search and use playlist"

# If we have just a search then go the search and play
if [[ ! -z "${search}" ]]; then
    echo "Playing based on search..."
    mpv --sub=no --audio-channels=stereo --audio-samplerate=48000 --no-audio-display --ytdl-format=bestaudio "ytdl://ytsearch:${search}"
fi

# If we have video, and the playlist param is not empty then play the playlist with video
if [[ "$VIDEO" = true ]] && [[ ! -z "$param" ]]; then
    echo "Playing Audio and Video..."
    mpv --audio-channels=stereo --audio-samplerate=48000 --ytdl-raw-options="yes-playlist=" ${param}
fi

if [[ "$VIDEO" = false ]] && [[ ! -z "$param" ]]; then
    echo "Playing Audio only..."
    mpv --sub=no --audio-channels=stereo --audio-samplerate=48000 --no-audio-display --ytdl-format=bestaudio --ytdl-raw-options="yes-playlist=" ${param}
fi

msg "- Invalid or no options set"
